version: "3"
services:
  database:
    image: "postgres:12.1"
    container_name: "booksjs-database"
    ports:
      - "5432:5432"
    volumes:
      - ./db-init/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: book
      POSTGRES_PASSWORD: book
      POSTGRES_DB: books_database
  # zipkin:
  #   image: "openzipkin/zipkin"
  #   container_name: "booksjs-zipkin"
  #   ports:
  #     - "9411:9411"
